### PR TITLE
Upd notify - add edit availability url

### PR DESCRIPTION
**Pull request by Kraaft**
-NOT SURE ABOUT MYSELF-

It is supposed to add a message that explain how to set yourself available (for the common case where someone has been late and want to stop the alternate search and play this round.)

I had to create the url via abs_url(reverse()) and if I got it right: edit_availability needs no argument.
I hope the syntax is correct though (meaning the 3 elements in <reverse> will not require 3 elements in <args=> cause I put only two.)

Please check that I've been a good boy. Thanks.

### CODE REVIEW

**Comment by lakinwecker** [comment]
Based on a cursory review, I don't see any reason why this won't work.

**Comment by lakinwecker** [comment]
I'm not sure how to test it easily, so I don't have time to test it today, but I'll look into it as soon as I can.

**Comment by cyanfish** [comment]
This is only applicable for the team league, but the method is also used for lonewolf. You'll want to put this behind a condition (like allow_continue below).

**Comment by cyanfish** [comment]
Thanks!

**Pull request closed without merging**
